name: Deploy Backend to EC2

on:
  push:
    branches: 
      - "main"
      - "dev"
    paths:
      - 'backend/**'
      - '.github/workflows/development_back.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Fetch Secrets from SSM
        id: fetch-secrets
        run: |
          DYNAMIC_URI=$(aws ssm get-parameter --name "/releaseforge/backend/mongo_uri" --with-decryption --query "Parameter.Value" --output text)
          DYNAMIC_IP=$(aws ssm get-parameter --name "/releaseforge/backend/ec2_public_ip" --query "Parameter.Value" --output text)

          GH_ID=$(aws ssm get-parameter --name "/releaseforge/backend/github_client_id" --with-decryption --query "Parameter.Value" --output text)
          GH_SECRET=$(aws ssm get-parameter --name "/releaseforge/backend/github_client_secret" --with-decryption --query "Parameter.Value" --output text)
          SESS_SECRET=$(aws ssm get-parameter --name "/releaseforge/backend/session_secret" --with-decryption --query "Parameter.Value" --output text)
          ENCRYPTION_KEY=$(aws ssm get-parameter --name "/releaseforge/backend/ENCRYPTION_KEY" --with-decryption --query "Parameter.Value" --output text)
          GITHUB_AUTH_URL=$(aws ssm get-parameter --name "/releaseforge/backend/GITHUB_AUTH_URL" --query "Parameter.Value" --output text)
          GEMINI_API_KEY=$(aws ssm get-parameter --name "/releaseforge/backend/GEMINI_API_KEY" --with-decryption --query "Parameter.Value" --output text)


          echo "::add-mask::$DYNAMIC_URI"
          echo "::add-mask::$GH_ID"
          echo "::add-mask::$GH_SECRET"
          echo "::add-mask::$SESS_SECRET"
          echo "::add-mask::$ENCRYPTION_KEY"
          echo "::add-mask::$GITHUB_AUTH_URL"
          echo "::add-mask::$GEMINI_API_KEY"
          
          echo "MONGO_URI=$DYNAMIC_URI" >> $GITHUB_ENV
          echo "EC2_HOST=$DYNAMIC_IP" >> $GITHUB_ENV
          echo "GH_CLIENT_ID=$GH_ID" >> $GITHUB_ENV
          echo "GH_CLIENT_SECRET=$GH_SECRET" >> $GITHUB_ENV
          echo "SESSION_SECRET=$SESS_SECRET" >> $GITHUB_ENV
          echo "ENCRYPTION_KEY=$ENCRYPTION_KEY" >> $GITHUB_ENV
          echo "GITHUB_AUTH_URL=$GITHUB_AUTH_URL" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> $GITHUB_ENV
          aws ssm get-parameter --name "/releaseforge/backend/ec2_private_key" --with-decryption --query "Parameter.Value" --output text > private_key.pem
          chmod 644 private_key.pem

      - name: Copy backend files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key_path: "private_key.pem" 
          source: "backend"
          target: "~/app"
          strip_components: 1 

      - name: Build and Run Docker containers (Backend + Nginx)
        uses: appleboy/ssh-action@v1.0.3
        env:
          MONGO_URI: ${{ env.MONGO_URI }}
          GH_CLIENT_ID: ${{ env.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ env.GH_CLIENT_SECRET }}
          SESSION_SECRET: ${{ env.SESSION_SECRET }}
          ENCRYPTION_KEY: ${{ env.ENCRYPTION_KEY }}
          GITHUB_AUTH_URL: ${{ env.GITHUB_AUTH_URL }}
          GEMINI_API_KEY: ${{ env.GEMINI_API_KEY }}
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key_path: "private_key.pem"
          envs: MONGO_URI, GH_CLIENT_ID, GH_CLIENT_SECRET, SESSION_SECRET, ENCRYPTION_KEY, GITHUB_AUTH_URL, GEMINI_API_KEY
          script: |
            cd ~/app
            echo "PORT=8080" > .env
            echo "MONGO_URI=$MONGO_URI" >> .env
            echo "EC2_HOST=$EC2_HOST" >> .env
            echo "GH_CLIENT_ID=$GH_CLIENT_ID" >> .env         
            echo "GH_CLIENT_SECRET=$GH_CLIENT_SECRET" >> .env
            echo "SESSION_SECRET=$SESSION_SECRET" >> .env
            echo "ENCRYPTION_KEY=$ENCRYPTION_KEY" >> .env
            echo "GITHUB_AUTH_URL=$GITHUB_AUTH_URL" >> .env
            echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> .env


            cat << 'EOF' > nginx.conf
            server {
                listen 80;
                client_max_body_size 50M;
                add_header X-Frame-Options "SAMEORIGIN";
                add_header X-XSS-Protection "1; mode=block";
                add_header X-Content-Type-Options "nosniff";
                
                location /api/ {
                    proxy_pass http://backend-server:8080;
                    proxy_connect_timeout 300;
                    proxy_send_timeout 300;
                    proxy_read_timeout 300;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_cache_bypass $http_upgrade;
                }
            }
            EOF
            
            sudo docker network inspect releaseforge-net >/dev/null 2>&1 || sudo docker network create releaseforge-net
            
            sudo docker stop backend-server nginx-server || true
            sudo docker rm backend-server nginx-server || true
            
            sudo docker build -t backend-server .
            sudo docker run -d --name backend-server --network releaseforge-net --env-file .env backend-server
            
            sudo docker run -d --name nginx-server --network releaseforge-net -p 80:80 -v $(pwd)/nginx.conf:/etc/nginx/conf.d/default.conf:ro nginx:alpine
      - name: Cleanup
        if: always()
        run: rm -f private_key.pem
        