name: Deploy static site to S3

on:
  push:
    branches: 
      - "main"
      - "dev"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        # env:
          # VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          # VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          # VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      
      - name: Debug context
        run: |
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          # role-to-assume: arn:aws:iam::666735446587:role/my-gitaction-for-summer
          aws-region: us-west-2

      - name: Sync site/ to S3 to \site/
        run: |
          aws s3 sync dist s3://dev-projectsummer.click/ --delete

      - name: Invalidate CloudFront cache
        run: |
           aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
